services:
  horde-auth:
    container_name: horde-auth
    build:
      context: .
      dockerfile: Dockerfile.auth
    ports:
      - "7777:8000"  # Porta per il serAver di autenticazione
    environment:
      FOURSQUARE_CLIENT_ID: EFV05TO0CPVRBFKGMKLMIF1DSP5G5DNDAMCYST0NQIUSUQLA
      FOURSQUARE_CLIENT_SECRET: WZUYLOJ1HKF0RYET033BMFL2MZECJI5GKSPR5EFZ035OZIVU
      REDIRECT_URI: https://reg.tanadelgigante.com/callback/
    volumes:
      - horde-data:/shared

  horde-rss:
    container_name: horde-rss
    build:
      context: .
      dockerfile: Dockerfile.rss
    ports:
      - "7778:8000"  # Porta per il server RSS
    environment:
      OUTPUT_FORMAT: rss
      OUTPUT_FILE: /shared/check_ins.xml
      SERVER_URL: http://dun-srv-app:7778
    volumes:
      - horde-data:/shared

volumes:
  horde-data:

      