# Usa l'immagine base python:3.9-slim
FROM python:3.9-slim

# Imposta la directory di lavoro
WORKDIR /app

# Copia gli script e il file di manifest nella directory di lavoro
COPY foursquare_checkin_publisher.py .
COPY manifest.json .

# Crea la directory static e copia il file CSS
RUN mkdir -p static
COPY static/horde.css static/

# Installa le dipendenze necessarie
RUN pip install --no-cache-dir requests feedgen flask

# Espone la porta 8000
EXPOSE 8000

# Comando per eseguire il server RSS
CMD ["python", "foursquare_checkin_publisher.py"]
